# Generated by Django 6.0.3 on 2026-03-16 13:03

import books.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, validators=[django.core.validators.MaxLengthValidator(200)])),
                ('isbn', models.CharField(max_length=13, validators=[books.models.validate_isbn])),
                ('publication_year', models.IntegerField()),
            ],
        ),
    ]
