# Generated by Django 6.0 on 2026-03-13 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_loginattempt_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
